// Auto-generated: image paths (relative to /public/assets) confirmed to have a
// real transparent background (checked for >2% actually-transparent pixels).
// Used to decide object-fit: only these render as letterboxed "contain" cutouts —
// everything else (opaque JPG/PNG, including lifestyle photography with its own
// baked-in backdrop) renders as "cover" so no mismatched background box shows.
export const transparentImages = new Set<string>([
  "products/men/men-abstract-print-long-sleeve-top.png",
  "products/men/men-abstract-print-lounge-set.png",
  "products/men/men-black-textured-crew-neck-sweater.png",
  "products/men/men-blue-textured-crew-neck-sweater.png",
  "products/men/men-brushed-plaid-overshirt.png",
  "products/men/men-button-neck-knit-sweater.png",
  "products/men/men-camp-collar-casual-shirt.png",
  "products/men/men-charcoal-crew-neck-sweater.png",
  "products/men/men-contrast-raglan-top.png",
  "products/men/men-contrast-trim-knit-shirt.png",
  "products/men/men-essential-striped-lounge-set.png",
  "products/men/men-graphic-cotton-blend-tshirt-ivory.png",
  "products/men/men-harvard-heritage-set-top.png",
  "products/men/men-harvard-heritage-set-trousers.png",
  "products/men/men-olive-casual-shirt.png",
  "products/men/men-olive-open-neck-knit-sweater.png",
  "products/men/men-quarter-zip-knit-sweater.png",
  "products/men/men-regular-fit-check-shirt.png",
  "products/men/men-slim-fit-stripe-shirt-blue.png",
  "products/men/men-stretch-tailored-formal-shirt.png",
  "products/men/men-striped-long-sleeve-top.png",
  "products/men/men-textured-crew-neck-sweater-mustard.png",
  "products/men/men-tonal-jacquard-tshirt-ivory.png",
  "products/men/men-v-neck-knit-vest-blue.png",
  "products/men/men-yale-collegiate-sweat-set-top.png",
  "products/men/men-yale-collegiate-sweat-set-trousers.png",
  "products/men/men-yarn-dyed-stripe-shirt.png",
  "products/lingerie/lingerie-black-smooth-bra.png",
  "products/lingerie/lingerie-cream-lace-bra.png",
  "products/lingerie/lingerie-ivory-sheer-lace-bra.png",
  "products/lingerie/lingerie-sage-smooth-molded-bra.png",
  "products/lingerie/lingerie-wine-lace-panel-bra.png",
  "products/kids/kids-astronaut-graphic-top.png",
  "products/kids/kids-cupcake-graphic-top.png",
  "products/kids/kids-metallic-flower-sweatshirt.png",
  "products/kids/kids-monster-pocket-sweatshirt.png",
  "products/kids/kids-monster-print-top.png",
  "products/kids/kids-paris-bow-graphic-top.png",
  "products/kids/kids-ruffle-star-sweatshirt.png",
]);
