// GENERATED by scripts/make-bundled-photos.mjs — do not edit by hand.
export type BundledPhoto = { path: string; group: string };

export const BUNDLED_PHOTOS: BundledPhoto[] = [
  {
    "path": "garment-quality-inspection.jpg",
    "group": "Other"
  },
  {
    "path": "logos/client-1.png",
    "group": "Logos"
  },
  {
    "path": "logos/client-2.png",
    "group": "Logos"
  },
  {
    "path": "logos/client-3.png",
    "group": "Logos"
  },
  {
    "path": "logos/member-1.png",
    "group": "Logos"
  },
  {
    "path": "logos/member-2.png",
    "group": "Logos"
  },
  {
    "path": "logos/member-3.png",
    "group": "Logos"
  },
  {
    "path": "premium-fabric-rolls-textures.jpg",
    "group": "Other"
  },
  {
    "path": "products/categories/activewear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/activewear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/denim-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/denim-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/kidswear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/kidswear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/knitwear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/knitwear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/menswear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/menswear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/sleepwear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/sleepwear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/womenswear-1.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/categories/womenswear-2.jpg",
    "group": "Product ranges"
  },
  {
    "path": "products/kids/kids-animal-print-tshirt.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-astronaut-graphic-top.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-bodysuit-mauve.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-car-graphic-tshirt-orange.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-car-print-tshirt-green.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-cupcake-graphic-top.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-dino-graphic-tshirt-navy.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-dungaree-dress-beige.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-floral-sleepsuit-pink.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-jungle-print-sleepsuit-red.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-metallic-flower-sweatshirt.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-monster-pocket-sweatshirt.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-monster-print-top.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-paris-bow-graphic-top.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-pocket-print-tshirt-blue.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-ruffle-star-sweatshirt.png",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-skater-graphic-tshirt-teal.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-star-print-sleepsuit.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-strawberry-frill-romper.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-striped-dungaree-yellow.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-teddy-graphic-tshirt-red.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-tie-dye-tshirt-orange.jpg",
    "group": "Kids"
  },
  {
    "path": "products/kids/kids-yacht-club-tshirt-green.jpg",
    "group": "Kids"
  },
  {
    "path": "products/lingerie/lingerie-black-smooth-bra.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-cream-lace-bra.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-crochet-bralette-cream.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-ivory-sheer-lace-bra.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-balconette-bra-blush.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-bra-black-satin.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-bra-blush-satin.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-bra-plum.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-bralette-ivory.jpg",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-lace-pushup-bra-nude.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-sage-smooth-molded-bra.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-sheer-lace-bra-peach.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-black.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-mauve.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-sage-green-racerback.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-sage-green.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-sage-grey.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-tshirt-bra-slate-grey.png",
    "group": "Lingerie"
  },
  {
    "path": "products/lingerie/lingerie-wine-lace-panel-bra.png",
    "group": "Lingerie"
  },
  {
    "path": "products/men/men-abstract-print-long-sleeve-top.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-abstract-print-lounge-set.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-black-textured-crew-neck-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-blue-textured-crew-neck-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-brushed-plaid-overshirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-button-neck-knit-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-camp-collar-casual-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-camp-collar-shirt-ivory.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-cargo-joggers-charcoal.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-cargo-pants-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-charcoal-crew-neck-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-chino-pants-beige.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-contrast-raglan-top.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-contrast-trim-knit-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-crew-tshirts-grey.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-essential-striped-lounge-set.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-flannel-overshirt-check.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-graphic-cotton-blend-tshirt-ivory.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-half-zip-sweater-cream.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-harvard-heritage-set-top.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-harvard-heritage-set-trousers.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-henley-tshirt-brown.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-hooded-puffer-olive-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-hooded-puffer-olive-mannequin.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-hybrid-softshell-jacket-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-jacquard-tshirt-ivory.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-olive-casual-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-olive-open-neck-knit-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-polo-shirt-beige.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-puffer-jacket-black-slim.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-quarter-zip-knit-sweater.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-quilted-hybrid-jacket-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-quilted-puffer-jacket-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-regular-fit-check-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-ribbed-tank-grey.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-slim-fit-stripe-shirt-blue.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-slim-shirt-black.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-stretch-tailored-formal-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-striped-long-sleeve-top.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-textured-crew-neck-sweater-mustard.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-tonal-jacquard-tshirt-ivory.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-track-jacket-olive.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-tshirt-beige.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-tshirt-graphic-blue.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-tshirt-graphic-ivory.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-turtleneck-sweater-charcoal.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-turtleneck-sweater-grey.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-v-neck-knit-vest-blue.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-vneck-sweater-grey.jpg",
    "group": "Men"
  },
  {
    "path": "products/men/men-yale-collegiate-sweat-set-top.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-yale-collegiate-sweat-set-trousers.png",
    "group": "Men"
  },
  {
    "path": "products/men/men-yarn-dyed-stripe-shirt.png",
    "group": "Men"
  },
  {
    "path": "products/women/women-bootcut-jeans-black.jpg",
    "group": "Women"
  },
  {
    "path": "products/women/women-crossover-waist-jeans-blue.jpg",
    "group": "Women"
  },
  {
    "path": "products/women/women-skinny-jeans-black.jpg",
    "group": "Women"
  },
  {
    "path": "products/women/women-striped-batwing-top-navy.jpg",
    "group": "Women"
  },
  {
    "path": "products/women/women-striped-midi-dress.jpg",
    "group": "Women"
  },
  {
    "path": "stacked-premium-fabric-rolls.jpg",
    "group": "Other"
  },
  {
    "path": "trims-accessories-flat-lay.jpg",
    "group": "Other"
  },
  {
    "path": "vid-01-poster.jpg",
    "group": "Other"
  }
];
